### ISSUE TITLE
How to fine tune this model?

### ISSUE THREAD

**Issue by yson7310** [fractalego/fact_checking#1]
Hi fractalego,

My name is Raina, and I am a university student currently doing my uni project. I really appreciate your effort in making this fact-checking model! Currently, my project is looking to validate facts in programming concepts, and we have manually labelled data. I am wondering if there is a way to fine-tune your model so that the model can be used for my purpose? If so, I would love to know how to do that. I am still a beginner in machine learning, so it would be very helpful if I could see the training script you used to train your current model based on the FEVER dataset, so I can have an idea of how to fine-tune it myself. 

I could not find any other ways to contact you, which is why I'm leaving an issue ticket here. I really hope you can see this ticket soon as I am urgently looking for help. (Please note, if you are worried, this action of seeking help from you is approved by my supervisor, so I'm not trying to ask you to help me do my homework!)

Thank you for all your understanding and help in advance!!!

Kind regards,
Raina

**Comment by fractalego** [comment]
Hi Raina, Thank you for your interest in this work! 

I have updated the original training notebook under the _notebook/_ folder as well the original training data in the _data/_ folder (zipped).

In principle, you can use the same script to fine tune the model on your data. Instead of starting from the base gpt2 model, you can use the fact-checker model that is on huggingface.

As an aside: This was a weekend project for me and did not expect it to become this popular. I did not use the best training procedure. Happy to learn if you find a way to improve it!

**Comment by yson7310** [comment]
Hi fractalego,

Thanks so much for those resources! They helped a lot with our fine-tuning, and we got good results with our labelled data!
